export const ACP = {
  AccessControlResource: "http://www.w3.org/ns/solid/acp#AccessControlResource",
  AccessControl: "http://www.w3.org/ns/solid/acp#AccessControl",
  Matcher: "http://www.w3.org/ns/solid/acp#Matcher",
  Policy: "http://www.w3.org/ns/solid/acp#Policy",
  accessControl: "http://www.w3.org/ns/solid/acp#accessControl",
  agent: "http://www.w3.org/ns/solid/acp#agent",
  client: "http://www.w3.org/ns/solid/acp#client",
  issuer: "http://www.w3.org/ns/solid/acp#issuer",
  vc: "http://www.w3.org/ns/solid/acp#vc",
  allow: "http://www.w3.org/ns/solid/acp#allow",
  deny: "http://www.w3.org/ns/solid/acp#deny",
  CreatorAgent: "http://www.w3.org/ns/solid/acp#CreatorAgent",
  OwnerAgent: "http://www.w3.org/ns/solid/acp#OwnerAgent",
  PublicAgent: "http://www.w3.org/ns/solid/acp#PublicAgent",
  AuthenticatedAgent: "http://www.w3.org/ns/solid/acp#AuthenticatedAgent",
  anyOf: "http://www.w3.org/ns/solid/acp#anyOf",
  allOf: "http://www.w3.org/ns/solid/acp#allOf",
  noneOf: "http://www.w3.org/ns/solid/acp#noneOf",
  apply: "http://www.w3.org/ns/solid/acp#apply",
  memberAccessControl: "http://www.w3.org/ns/solid/acp#memberAccessControl",
  mode: "http://www.w3.org/ns/solid/acp#mode",
  resource: "http://www.w3.org/ns/solid/acp#resource",
} as const;
