export const VCARD = {
  fn: "http://www.w3.org/2006/vcard/ns#fn",
  email: "http://www.w3.org/2006/vcard/ns#email",
  hasEmail: "http://www.w3.org/2006/vcard/ns#hasEmail",
  hasValue: "http://www.w3.org/2006/vcard/ns#hasValue",
  hasPhoto: "http://www.w3.org/2006/vcard/ns#hasPhoto",
  hasTelephone: "http://www.w3.org/2006/vcard/ns#hasTelephone",
  title: "http://www.w3.org/2006/vcard/ns#title",
  hasUrl: "http://www.w3.org/2006/vcard/ns#hasUrl",
  organizationName: "http://www.w3.org/2006/vcard/ns#organization-name",
  phone: "http://www.w3.org/2006/vcard/ns#phone",
  role: "http://www.w3.org/2006/vcard/ns#role",
  value: "http://www.w3.org/2006/vcard/ns#value",
  telephoneType: "http://www.w3.org/2006/vcard/ns#TelephoneType",
} as const;
